---
- name: add to address-group
  hosts: all
  connection: local
  
  collections:
      - paloaltonetworks.panos
      
  vars:
    device:
      ip_address: "{{ ansible_host }}"
      username: "admin"
      password: "Networkjourney@123"
  tasks:
  - name: CREATE ADDRESS
    panos_address_object:
      provider: '{{ device }}'
      name: 'deep_object_7'
      address_type: 'ip-netmask'
      value: '1.1.1.14'
  - name: CREATE ADDRESS
    panos_address_object:
      provider: '{{ device }}'
      name: 'deep_object_8'
      address_type: 'ip-netmask'
      value: '1.1.1.18'
  - name: create address-group
    panos_address_group:
      name: 'obgr_1'
      provider: '{{device}}'
      static_value: ['deep_object_7','deep_object_3','deep_object_4']
